apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sukt-platform-admin
  name: sukt-platform-admin
  namespace: sukt-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sukt-platform-admin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sukt-platform-admin
    spec:
      containers:
      - name: sukt-platform-admin
        image: registry.cn-hangzhou.aliyuncs.com/sukt-platform/sukt-admin-api:develop.87   # 这个版本有办法获取到吗？  ${{ github.run_number }} 我是用的这个大的tag   就差这个了
        imagePullPolicy: IfNotPresent
        livenessProbe:
            httpGet:
              path: /api/healthchecks/liveness
              port: 80
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30 
              # timeoutSeconds: 60
        readinessProbe:
          httpGet: 
            path: /api/healthchecks/readiness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60 
            # timeoutSeconds: 60
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
            - mountPath: /app/appsettings.json # 这个对应的是容器内的地址
              name: appsettings
              readOnly: true
              subPath: appsettings.json # #这个位置对应的是comfigmap中的名字，不是 /usr/local/apisix-dashboard/conf/conf.yaml的
            - mountPath: /app/skyapm.json # 这个对应的是容器内的地址
              name: skyapm
              readOnly: true
              subPath: skyapm.json # #这个位置对应的是comfigmap中的名字，不是 /usr/local/apisix-dashboard/conf/conf.yaml的
        env:
          - name: ASPNETCORE_HOSTINGSTARTUPASSEMBLIES # 需要通过映射的方式传入，不能通过Dockerfile的方式默认
            value: SkyAPM.Agent.AspNetCore
      restartPolicy: Always
      imagePullSecrets:
        - name: aliyun-iamge-secret
      volumes:
        - configMap:
            defaultMode: 420
            name:  sukt-admin-appsettings
          name: appsettings
        - configMap:
            defaultMode: 420
            name:  skyapm
          name: skyapm
---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: sukt-platform-admin
#   name: sukt-platform-admin
#   namespace: sukt-platform
# spec:
#   selector:
#     app: sukt-platform-admin
#   ports:
#   - port: 80
#     targetPort: 80
#   type: ClusterIP

apiVersion: v1
kind: Service
metadata:
  labels:
    app: sukt-platform-admin-nodetype
  name: sukt-platform-admin-nodetype
  namespace: sukt-platform
spec:
  type: NodePort
  selector:
    app: sukt-platform-admin
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30210

