name: Sukt.Core.API
on:
  push:
    branches: [dev/suktauthserver]
  pull_request:
    branches: [dev/suktauthserver]
env:
   IMAGE_NAME: registry.cn-hangzhou.aliyuncs.com/suktcore/sukt-core-admin-api
   IMAGE_TAG: $(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: dotnet restore #还原包
      run: dotnet restore src/Sukt.Core.API
    - name: dotnet publish #发布项目
      run: dotnet publish src/Sukt.Core.API --configuration -c Release --no-restore -o app  
    - name: Login To Docker #登录到镜像仓库
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.ALIYUN_DOCKER_IMAGESTORE_USERNAME }}
        password: ${{ secrets.ALIYUN_DOCKER_IMAGESTORE_PASSWORD }}
        registry: registry.cn-hangzhou.aliyuncs.com/suktcore/sukt-core-admin-api #镜像仓库地址
    - name: Run Crrpath
      run: ls 
    - name: Copy Dockerfile  # 拷贝Dockerfile到发布目录 ##生成随机数 echo "$RANDOM"|md5sum|cut -c 5-15
      run: cp Dockerfile /home/runner/work/Sukt.Core/Sukt.Core/app
    - name: Run path
      run: ls /home/runner/work/Sukt.Core/Sukt.Core/app
    - name: Build Docker Image # Build Docker镜像并推送到镜像仓库
      uses: docker/build-push-action@v2
      with:
        tags: $IMAGE_NAME:$IMAGE_TAG  #动态变量镜像名称和版本  #registry.cn-hangzhou.aliyuncs.com/suktcore/sukt-core-admin-api:v1.6 
        context: /home/runner/work/Sukt.Core/Sukt.Core/app
        file: /home/runner/work/Sukt.Core/Sukt.Core/app/Dockerfile # 指定Dockerfile
        push: true
      # run: |
      #   docker version
      #   # 登录到阿里云镜像仓库
      #   sudo docker login --username=${{secrets.ALIYUN_DOCKER_IMAGESTORE_USERNAME}} --password=${{ secrets.ALIYUN_DOCKER_IMAGESTORE_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
      #   docker build  --tag  registry.cn-hangzhou.aliyuncs.com/suktcore/sukt-core-admin-api:v1.6 -f Dockerfile ..
